sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1
      dist: precise

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/wenprise-term-group/
    - GH_REF: https://github.com/iwillhappy1314/wenprise-term-group.git
    - secure: "HLmT8DlQ+aoEMpKrZQrPNVY9Ii1k1wewyP0byM/7ZB4IADSTqm9jLvIoOkKP3NjSoF+UJoKmmg3Mc0eOd2enn7N98T34LusaUVLUOPIveerhQmlltBzVIG2r/rO3FlRX9vqyEe1oPsVUVzDtOvasCOhCg27x+0SbtYp45WjMxc9d9Cka/b5dSubiprj2sLZ/6qVGqVRvXIenhasn1yl6XNM47XhDGS9IWAkjkeBReUdA9WsP0A05VX6gs94zOaMgS/sUvzLZ6Th7qi+fSOGv79tTfRIT7m/hXrup1n2d0lAqONMaLycXLZgZwOELPXehRg47tNIFivN1WAhoEBhYMyNJZtwuHq+uRUQVbVLrsBQZPe31ga/eWRWzCrQkLiH76gFOqCYhqrQ7f2Q0Y1UuUSnkxtXAEybqchv5QlfuWquZXfxVSjvu0c4I6IgOs0/jrVpWQpNH/1JAM1ulW+bZIS8rNARu+sj6ysg2QfpX0tQIY+QzzW5H/fIIdwInBLsSAv2ULnHMlIewKM4pCgbEEXKsOksVbO2hJC3eOv+1dN6pHUyEfh5pMg/mryGMv95cAy0NcockDXRVtrewyEDN86Y7qc/PSoHwas5MY6k6iwqmhgjg8nErcsgZIH3HhN6kOFV6uqLet8f3J4OKqaPDcvNEXvF7gEDVFL1NKVI4UyM="

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
